import {useEffect,useMemo,useRef,useState} from "react"; import {Canvas,useFrame} from "@react-three/fiber"; import {OrbitControls,Grid} from "@react-three/drei"; import * as THREE from "three";
import TelemetryPanel from "./components/TelemetryPanel";
import MissionMonitor from "./components/MissionMonitor";
const API="http://localhost:5000/api";
const initialObstacles=[{position:{x:18,y:5,z:0},size:{x:8,y:10,z:10},type:"STATIC"},{position:{x:38,y:8,z:8},size:{x:8,y:16,z:8},type:"STATIC"},{position:{x:52,y:4,z:-12},size:{x:12,y:8,z:8},type:"STATIC"}];
function Drone({p}){const g=useRef();useFrame((_,d)=>{if(g.current)g.current.rotation.y+=d*1.5});return <group ref={g} position={[p.x,p.y,p.z]}><mesh><boxGeometry args={[2.5,.7,2]}/><meshStandardMaterial/></mesh>{[[1.8,.4],[1.8,-.4],[-1.8,.4],[-1.8,-.4]].map((m,i)=><group key={i} position={[m[0],.2,m[1]]}><mesh><cylinderGeometry args={[.12,.12,.3,12]}/><meshStandardMaterial/></mesh><mesh rotation={[Math.PI/2,0,0]}><boxGeometry args={[1.3,.06,.12]}/><meshStandardMaterial/></mesh></group>)}</group>}
function Box({o}){return <mesh position={[o.position.x,o.position.y,o.position.z]}><boxGeometry args={[o.size.x,o.size.y,o.size.z]}/><meshStandardMaterial transparent opacity={.55}/></mesh>}
function Route({path}){const pts=useMemo(()=>path.map(p=>new THREE.Vector3(p.x,p.y,p.z)),[path]);if(pts.length<2)return null;return <line><bufferGeometry attach="geometry" setFromPoints={pts}/><lineBasicMaterial/></line>}
function App(){const [pos,setPos]=useState({x:0,y:2,z:0}),[target,setTarget]=useState({x:65,y:12,z:0}),[path,setPath]=useState([]),[gps,setGps]=useState(true),[auto,setAuto]=useState(false),[status,setStatus]=useState("READY"),[phase,setPhase]=useState("IDLE"),[speed,setSpeed]=useState(0),[mission,setMission]=useState(null);const idx=useRef(0);const home={x:0,y:2,z:0};
 async function calculate(from=pos,to=target){const r=await fetch(API+"/routes/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start:from,goal:to,obstacles:initialObstacles})});const d=await r.json();setPath(d.route||[]);idx.current=0;return d.route||[]}
 async function create(){const p=await calculate();const r=await fetch(API+"/missions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start:home,target,route:p,gpsStatus:gps?"CONNECTED":"DENIED",status:"READY",phase:"PLANNED"})});setMission(await r.json());setStatus("MISSION CREATED")}
 function start(){if(!path.length){setMessage("Calculate a route first");return;}setAuto(true);setStatus(gps?"AUTONOMOUS":"EMERGENCY AUTOPILOT");setPhase(gps?"NAVIGATING":"GPS-DENIED NAVIGATION");setMessage("Autonomous navigation active")}
 function stop(){setAuto(false);setSpeed(0);setStatus("STOPPED");setPhase("MANUAL");setMessage("Mission paused")}
 function addObstacle(){const o={position:{x:Math.min(pos.x+7,target.x),y:pos.y,z:pos.z},size:{x:5,y:5,z:5},type:"DYNAMIC"};setObstacles(v=>[...v,o]);setMessage("Dynamic obstacle injected")}
 useEffect(()=>{if(!auto)return;const t=setInterval(()=>{const n=path[idx.current];if(!n){setAuto(false);setSpeed(0);setStatus("TARGET REACHED");setPhase("LANDING");return}setPos(n);setSpeed(12);idx.current++},220);return()=>clearInterval(t)},[auto,path]);
 useEffect(()=>{if(status!=="TARGET REACHED")return;const t=setTimeout(async()=>{setStatus("LANDED");setPhase("WAITING 10s");await new Promise(r=>setTimeout(r,10000));const p=await calculate(pos,home);setPath(p);idx.current=0;setAuto(true);setStatus("RETURNING HOME");setPhase("RETURN TO HOME")},1000);return()=>clearTimeout(t)},[status]);
 useEffect(()=>{if(status!=="RETURNING HOME")return;if(path.length&&idx.current>=path.length){setAuto(false);setSpeed(0);setStatus("MISSION COMPLETE");setPhase("HOME LANDED")}},[pos,status,path]);
 const disconnect=()=>{setGps(v=>!v);if(gps){setStatus("EMERGENCY AUTOPILOT");setPhase("GPS DENIED")}else{setStatus("READY");setPhase("GPS RESTORED")}};
 useEffect(()=>{if(!mission?._id)return;const t=setInterval(()=>{fetch(API+"/telemetry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId:mission._id,position:pos,altitude:pos.y,speed,gpsStatus:gps?"CONNECTED":"DENIED",obstacleDetected:sensor})}).catch(()=>{})},500);return()=>clearInterval(t)},[mission,pos,speed,gps,sensor]);
 const distance=Math.hypot(pos.x-target.x,pos.y-target.y,pos.z-target.z);
 return <div className="app"><header><div><h1>NAVIGATE-X</h1><p>GPS-DENIED AUTONOMOUS NAVIGATION SIMULATOR</p></div><span className={gps?"ok":"danger"}>● GPS {gps?"CONNECTED":"DENIED"}</span></header><main><section className="scene"><Canvas camera={{position:[90,60,90],fov:50}}><ambientLight intensity={1}/><directionalLight position={[20,50,10]} intensity={2}/><Grid args={[120,120]} sectionSize={5} cellSize={1}/><Drone p={pos}/><Route path={path}/><mesh position={[target.x,target.y,target.z]}><sphereGeometry args={[2,20,20]}/><meshStandardMaterial/></mesh>{initialObstacles.map((o,i)=><Box o={o} key={i}/>) }<OrbitControls/></Canvas></section><aside><h2>Mission Control</h2><label>Target X<input type="number" value={target.x} onChange={e=>setTarget({...target,x:+e.target.value})}/></label><label>Target Y<input type="number" value={target.y} onChange={e=>setTarget({...target,y:+e.target.value})}/></label><label>Target Z<input type="number" value={target.z} onChange={e=>setTarget({...target,z:+e.target.value})}/></label><button onClick={()=>calculate()}>Calculate 3D A*</button><button onClick={create}>Create Mission</button><button onClick={start}>Start Autonomous Mission</button><button onClick={stop}>Stop Mission</button><button onClick={addObstacle}>+ Inject Dynamic Obstacle</button><button className="warn" onClick={disconnect}>{gps?"Disconnect GPS":"Restore GPS"}</button><MissionMonitor status={status} phase={phase} gps={gps} waypoints={path.length} missionId={mission?._id}/><TelemetryPanel data={{...pos,altitude:pos.y,speed,distance}}/><div className="message">{message}</div><div className="cards"><b>STATUS<br/><span>{status}</span></b><b>PHASE<br/><span>{phase}</span></b><b>POSITION<br/><span>{pos.x.toFixed(1)}, {pos.y.toFixed(1)}, {pos.z.toFixed(1)}</span></b><b>SPEED<br/><span>{speed} m/s</span></b><b>DISTANCE<br/><span>{distance.toFixed(1)} m</span></b><b>WAYPOINTS<br/><span>{path.length}</span></b></div></aside></main></div>}
export default App;